version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
      timezone: "America/Denver"
    commit-message:
      prefix: "github-actions"
      include: "scope"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
      timezone: "America/Denver"
    commit-message:
      prefix: "nuget"
      include: "scope"
