name: critter-stacking

networks:
  critter-stacking:
    driver: bridge

volumes:
  postgres:
  pgadmin:

services:

  postgres:
    container_name: postgres
    image: postgres:17.0-alpine3.20
    restart: unless-stopped
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - critter-stacking

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:2024-10-19-2
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - critter-stacking
