name: Critter Stacking

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: .NET CI
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Cache .NET packages
        uses: actions/cache@v4.1.1
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: nuget-cache-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-cache=${{ runner.os }}-

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4.0.1
        with:
          global-json-file: global.json

      - name: Update DotNet Workloads
        run: dotnet workload update

      - name: Restore dependencies
        run: dotnet restore CritterStacking.sln

      - name: Build the application
        run: dotnet build CritterStacking.sln --configuration Release --no-restore

      - name: Test the application
        run: dotnet test CritterStacking.sln --configuration Release --no-build --verbosity normal --collect "XPlat Code Coverage" --results-directory ./coverage

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '10 10'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2.9.0
        with:
          recreate: true
          path: code-coverage-results.md
